trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: ScreenResolutionUtility@1
  inputs:
    displaySettings: 'specific'
    width: '1920'
    height: '1080'
- task: katalonTask@0
  displayName: 'Execute Katalon Studio project'
  inputs:
    version: '7.9.1'
    executeArgs: '-retry=0 -statusDelay=20 -testSuitePath="Test Suites/New Test Suite" -browserType="Firefox" -apiKey=$(katalon_api_key)'
