trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: S3Download@1
  inputs:
    awsCredentials: 'aws'
    regionName: 'us-east-1'
    bucketName: 'katalon'
    sourceFolder: '$(VERSION)'
    globExpressions: '@(Katalon_Studio_Engine_Windows_64)*.zip'
    targetFolder: '$(TMP_DIR)'
    displayName: Download KSE and KRE

- bash: |
    set -xe
    cd ${TMP_DIR}/${VERSION}
    unzip Katalon_Studio_Windows_64-${VERSION}.zip
  displayName: Extract KSR and KRE