trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: ScreenResolutionUtility@1
  inputs:
    displaySettings: 'specific'
    width: '1600'
    height: '900'
- task: katalonTask@0
  displayName: 'Execute Katalon Studio project - 1st'
  inputs:
    version: '7.9.1'
    executeArgs: '-retry=0 -statusDelay=15 -testSuitePath="Test Suites/New Test Suite" -browserType="Chrome (headless)" -apiKey=$(katalon_api_key)'
    