trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: katalonTask@0
  displayName: 'Execute Katalon Studio project'
  inputs:
    version: '7.8.1'
    executeArgs: '-retry=0 -statusDelay=15 -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey=$(katalon_api_key)'