trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: katalonTask@0
  displayName: 'Execute Katalon Studio project'
  inputs:
    version: '8.0.5'
    executeArgs: '-retry=0 -statusDelay=20 -testSuitePath="Test Suites/New Test Suite" -browserType="Chrome" -apiKey=$(katalon_api_key)'
