trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: katalonTask@1
  displayName: 'Execute Katalon Studio project'
  inputs:
    version: '8.0.5'
    executeArgs: '-testSuitePath="Test Suites/New Test Suite" -browserType="Chrome" -apiKey=$(katalon_api_key)'
    xvfbConfiguration: '-a -n 0 -s "-screen 0 1024x768x24"'
